# Generated by Django 5.2.8 on 2026-03-04 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_item_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='condition',
            field=models.CharField(choices=[('new', 'Brand New'), ('like_new', 'Like New / Open Box'), ('good', 'Good / Used'), ('fair', 'Fair / Acceptable')], default='good', max_length=20),
        ),
    ]
