# Generated by Django 5.2.8 on 2026-03-05 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_item_condition'),
        ('item', '0004_auto_20260305_0052'),
    ]

    operations = [
    ]
