# Generated by Django 5.2.8 on 2026-03-05 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_merge_0003_item_condition_0004_auto_20260305_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('sold', 'Sold'), ('delisted', 'Delisted'), ('hidden', 'Hidden'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=10),
        ),
    ]
