# Generated by Django 5.2.8 on 2026-03-06 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_alter_item_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='rating_avg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='item',
            name='rating_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='rating_sum',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
