# Generated by Django 5.2.8 on 2026-03-04 15:30

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_item_stock'),
        ('order', '0002_rename_item_order_item'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='price',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='created_at',
            new_name='created_time',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='buyer',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='Item',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='order_number',
            new_name='order_id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='paid_at',
            new_name='paid_time',
        ),
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantity'),
        ),
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='basket', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BasketItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.basket')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.item')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('basket', 'item'), name='uniq_basket_item')],
            },
        ),
    ]
